# ============================================================
# client-baseline module — input variables
# Technicians: you do NOT edit this file. All values are set in
# the client's terraform.tfvars file.
# ============================================================

variable "client_name" {
  description = "Client display name. Used in resource names inside Jamf Pro / Jamf Protect."
  type        = string
}

# ------------------------------------------------------------
# Jamf Protect baseline
# ------------------------------------------------------------

variable "enable_jamf_protect" {
  description = "Deploy the Jamf Protect baseline (plan, telemetry, action config) and push its configuration profile through Jamf Pro."
  type        = bool
  default     = true
}

variable "deploy_jamf_protect_profile" {
  description = "Deploy the Protect plan's configuration profile through Jamf Pro. OFF by default (2026-08-01): the provider-generated profile has issues without the Platform-level API — deploy the profile from the Jamf Protect console instead. The plan/telemetry/action config are managed regardless."
  type        = bool
  default     = false
}

variable "jamf_protect_mode" {
  description = "Threat prevention posture for the Jamf Protect plan. 'Block and report' for production, 'Report only' for a monitoring-first rollout."
  type        = string
  default     = "Block and report"

  validation {
    condition     = contains(["Block and report", "Report only"], var.jamf_protect_mode)
    error_message = "jamf_protect_mode must be exactly 'Block and report' or 'Report only'."
  }
}

# NOTE: all Jamf Platform features (software update Blueprints, passcode
# policy, CIS benchmark) live in modules/client-platform, loaded via the
# client folder's optional platform.tf. See that module for why.

# ------------------------------------------------------------
# Security baseline & enrollment
# ------------------------------------------------------------

variable "client_checkin_frequency" {
  description = "Minutes between Jamf client check-ins (tenant-wide singleton). MSP standard: 15."
  type        = number
  default     = 15

  validation {
    condition     = contains([5, 15, 30, 60], var.client_checkin_frequency)
    error_message = "client_checkin_frequency must be 5, 15, 30, or 60 (Jamf Pro's allowed values)."
  }
}

variable "enable_security_baseline" {
  description = "Deploy the security pack: FileVault enforcement + key escrow, screen lock profile, firewall profile, stale-device smart group."
  type        = bool
  default     = true
}

variable "screen_lock_idle_minutes" {
  description = "Minutes of idle before the screen saver starts (password required immediately)."
  type        = number
  default     = 15
}

variable "enable_prestage" {
  description = "Create the ADE/zero-touch PreStage enrollment. Requires the tenant's ABM link (ADE token) to exist first."
  type        = bool
  default     = true
}

variable "ade_instance_id" {
  description = "Jamf Pro Automated Device Enrollment instance ID (usually '1' for the first ABM token in a fresh tenant)."
  type        = string
  default     = "1"
}

variable "msp_admin_username" {
  description = "Username of the hidden MSP service admin created on EVERY Mac (lockout protection / support access). Created at enrollment by the PreStage and self-healed by policy."
  type        = string
  default     = "msp_admin"
}

variable "msp_admin_password" {
  description = "Per-client password for the MSP service admin. Required - the account is part of the baseline on every Mac. Rotate by changing this value and re-applying."
  type        = string
  default     = ""
  sensitive   = true
}

variable "support_email" {
  description = "Support email shown during enrollment."
  type        = string
  default     = "helpdesk@example.com"
}

# ------------------------------------------------------------
# EDR — Huntress OR SentinelOne (pick one per client)
# ------------------------------------------------------------

variable "edr_provider" {
  description = "Which EDR this client uses: 'huntress', 'sentinelone', or 'none'."
  type        = string

  validation {
    condition     = contains(["huntress", "sentinelone", "none"], var.edr_provider)
    error_message = "edr_provider must be 'huntress', 'sentinelone', or 'none'."
  }
}

variable "huntress_account_key" {
  description = "Huntress Account Key (from the Huntress portal). Required when edr_provider = 'huntress'."
  type        = string
  default     = ""
  sensitive   = true
}

variable "huntress_organization_key" {
  description = "Huntress Organization Key for this client (usually the client name as it appears in Huntress). Required when edr_provider = 'huntress'."
  type        = string
  default     = ""
}

variable "sentinelone_site_token" {
  description = "SentinelOne Site Token for this client's site. Required when edr_provider = 'sentinelone'."
  type        = string
  default     = ""
  sensitive   = true
}

variable "sentinelone_package_path" {
  description = "Local path to the SentinelOne installer pkg (from the repo's packages/ folder, e.g. ../../packages/Sentinel-Release_macos_v25_3_1_8253.pkg). Terraform uploads it to the tenant JCDS and attaches it to the install policy (Cache). Required when edr_provider = 'sentinelone'."
  type        = string
  default     = ""
}

variable "huntress_package_path" {
  description = "Optional local path to a Huntress agent pkg. Uploaded to JCDS as an offline fallback only - the install policy uses Huntress's self-downloading script."
  type        = string
  default     = ""
}

# ------------------------------------------------------------
# Splashtop
# ------------------------------------------------------------

variable "enable_splashtop" {
  description = "Create the Splashtop Streamer deployment scaffolding (script, smart group, policy)."
  type        = bool
  default     = true
}

variable "splashtop_deploy_code" {
  description = "Splashtop deployment (stream) code for this client, from the Splashtop web console under Management > Deployment."
  type        = string
  default     = ""
  sensitive   = true
}

variable "splashtop_package_path" {
  description = "Local path to the Composer-built Splashtop Streamer deploy pkg (e.g. ../../packages/SplashtopStreamerDeploy.pkg). Terraform uploads it to the tenant JCDS and attaches it to the install policy."
  type        = string
  default     = ""
}

# ------------------------------------------------------------
# Self Service apps (Jamf App Installers)
# ------------------------------------------------------------

variable "is_1password_customer" {
  description = "Is this client a 1Password customer? true = 1Password is installed automatically on all Macs and kept up to date."
  type        = bool
  default     = false
}

variable "common_apps_scope" {
  description = "Scope for the common-app App Installers. 'all' (default): every Mac sees them in Self Service and installed copies auto-patch. 'installed_only': scope to the 'Has <app>' smart groups — auto-patch existing installs only, hidden from Macs without the app."
  type        = string
  default     = "all"

  validation {
    condition     = contains(["all", "installed_only"], var.common_apps_scope)
    error_message = "common_apps_scope must be 'all' or 'installed_only'."
  }
}

variable "app_suite" {
  description = "Which productivity suite to offer in Self Service. 'auto' (default) follows idp_provider: Entra clients get the Microsoft 365 suite, Google Workspace clients get the Google apps. Override with 'microsoft', 'google', or 'none'. Core apps (Acrobat Reader, Teams, Zoom, Chrome) are always offered."
  type        = string
  default     = "auto"

  validation {
    condition     = contains(["auto", "microsoft", "google", "none"], var.app_suite)
    error_message = "app_suite must be 'auto', 'microsoft', 'google', or 'none'."
  }
}

# ------------------------------------------------------------
# Jamf Connect — Entra ID OR Google Workspace (pick one per client)
# ------------------------------------------------------------

variable "idp_provider" {
  description = "Identity provider for Jamf Connect: 'entra', 'google', or 'none' (client does not receive Jamf Connect - no profiles are deployed)."
  type        = string

  validation {
    condition     = contains(["entra", "google", "none"], var.idp_provider)
    error_message = "idp_provider must be 'entra', 'google', or 'none'."
  }
}

variable "jamf_connect_oidc_client_id" {
  description = "OIDC client ID for Jamf Connect. Entra: the Application (client) ID of the Jamf Connect app registration. Google: the OAuth client ID. Leave empty when idp_provider = 'none'."
  type        = string
  default     = ""
}

variable "jamf_connect_entra_tenant_id" {
  description = "Entra ID Directory (tenant) ID. Required when idp_provider = 'entra'. Leave empty for Google."
  type        = string
  default     = ""
}

variable "jamf_connect_redirect_uri" {
  description = "OIDC redirect URI configured on the IdP app registration for Jamf Connect."
  type        = string
  default     = "https://127.0.0.1/jamfconnect"
}

variable "jamf_connect_license_b64" {
  description = "Optional: Jamf Connect license file content, base64-encoded. Leave empty to skip the license profile (e.g., during a trial)."
  type        = string
  default     = ""
  sensitive   = true
}

variable "enable_platform_sso" {
  description = "Deploy Microsoft Entra Platform SSO alongside Jamf Connect (Entra clients only - ignored when idp_provider is 'google' or 'none'). Adds the PSSO profile, pushes Company Portal, sets the PreStage PSSO fields, and creates the registration EA + smart group."
  type        = bool
  default     = true
}

variable "jamf_connect_deny_local" {
  description = "Force all logins through the IdP (DenyLocal). Excluded accounts (PreStage admin + jamf_connect_excluded_local_accounts) can still log in locally. LocalFallback remains on for IdP outages."
  type        = bool
  default     = true
}

variable "jamf_connect_excluded_local_accounts" {
  description = "Extra local account usernames excluded from DenyLocal and hidden from migration (the hidden PreStage admin is always included automatically)."
  type        = list(string)
  default     = []
}

variable "jamf_connect_admin_group" {
  description = "Optional IdP group whose members get local admin rights at account creation (OIDCAdmin). Empty = all IdP-created users are standard. Requires the groups claim on the IdP app registration."
  type        = string
  default     = ""
}

variable "jamf_connect_migrate" {
  description = "Takeover clients: let users link their existing local account to their IdP identity at first login (Migrate + MigrateUsersHide). Off for greenfield fleets."
  type        = bool
  default     = false
}

variable "jamf_connect_help_url" {
  description = "URL behind the Help button at the Jamf Connect login window. Empty = no help button."
  type        = string
  default     = "https://example.com"
}

variable "company_portal_package_path" {
  description = "Local path to the Microsoft Company Portal pkg (download from https://go.microsoft.com/fwlink/?linkid=853070 into the repo's packages/ folder, e.g. ../../packages/CompanyPortal-Installer.pkg). Required when Platform SSO is enabled for an Entra client. Microsoft requires a current version - old versions break PSSO."
  type        = string
  default     = ""
}

variable "enable_jamf_connect_menubar" {
  description = "Also deploy the Jamf Connect menu bar app profile. Default false: validate the generated template with the Jamf Connect Configuration app before enabling."
  type        = bool
  default     = false
}
