# Provider configuration for this client.
# Technicians: you do NOT edit this file. Credentials come from terraform.tfvars.

terraform {
  required_version = ">= 1.13.0"

  required_providers {
    jamfpro = {
      source = "deploymenttheory/jamfpro"
    }
    jamfprotect = {
      source = "Jamf-Concepts/jamfprotect"
    }
    jamfplatform = {
      source = "Jamf-Concepts/jamfplatform"
    }
  }
}

# Auth: "oauth2" (API client - MSP standard for client tenants) or
# "basic" (a LOCAL Jamf Pro admin account's username/password - handy for
# sandbox tests; SSO-backed admins cannot basic-auth to the API).
provider "jamfpro" {
  jamfpro_instance_fqdn = var.jamfpro_instance_fqdn
  auth_method           = var.jamfpro_auth_method

  client_id     = var.jamfpro_client_id
  client_secret = var.jamfpro_client_secret

  basic_auth_username = var.jamfpro_basic_username
  basic_auth_password = var.jamfpro_basic_password

  # Recommended by the provider for Jamf Cloud tenants (sticky session
  # across the load balancer so resources are read back reliably).
  jamfpro_load_balancer_lock = true
}

provider "jamfprotect" {
  url           = var.jamfprotect_url
  client_id     = var.jamfprotect_client_id
  client_secret = var.jamfprotect_client_secret
}

# The jamfplatform provider block lives in platform.tf (rename
# platform.tf.off -> platform.tf to enable Platform features for this
# client). It cannot live here: the provider AUTHENTICATES during
# `terraform plan` even when every Platform feature is disabled
# (VERIFIED live 2026-08-01), so clients without Platform API access
# must not load it at all.
