# Variable declarations for this client folder.
# Technicians: you do NOT edit this file — set values in terraform.tfvars.

# ── Client ───────────────────────────────────────────────────
variable "client_name" {
  description = "Client display name (used in resource names)."
  type        = string
}

# ── Jamf Pro tenant ──────────────────────────────────────────
variable "jamfpro_instance_fqdn" {
  description = "Jamf Pro URL, e.g. https://acmecorp.jamfcloud.com"
  type        = string
}

variable "jamfpro_auth_method" {
  description = "'oauth2' (API client - standard) or 'basic' (local Jamf Pro admin username/password - sandbox convenience; SSO admins cannot basic-auth)."
  type        = string
  default     = "oauth2"

  validation {
    condition     = contains(["oauth2", "basic"], var.jamfpro_auth_method)
    error_message = "jamfpro_auth_method must be 'oauth2' or 'basic'."
  }
}

variable "jamfpro_client_id" {
  description = "Jamf Pro API Client ID (Settings > API roles and clients). Required when jamfpro_auth_method = 'oauth2'."
  type        = string
  default     = ""
  sensitive   = true
}

variable "jamfpro_client_secret" {
  description = "Jamf Pro API Client Secret (shown once when created). Required when jamfpro_auth_method = 'oauth2'."
  type        = string
  default     = ""
  sensitive   = true
}

variable "jamfpro_basic_username" {
  description = "Local Jamf Pro admin username. Required when jamfpro_auth_method = 'basic'. MSP standard account: msp_terraform."
  type        = string
  default     = "msp_terraform"
  sensitive   = true
}

variable "jamfpro_basic_password" {
  description = "Local Jamf Pro admin password. Required when jamfpro_auth_method = 'basic'."
  type        = string
  default     = ""
  sensitive   = true
}

# ── Jamf Protect tenant ──────────────────────────────────────
variable "jamfprotect_url" {
  description = "Jamf Protect URL, e.g. https://acmecorp.protect.jamfcloud.com"
  type        = string
}

variable "jamfprotect_client_id" {
  description = "Jamf Protect API Client ID (Administrative > API Clients)."
  type        = string
  sensitive   = true
}

variable "jamfprotect_client_secret" {
  description = "Jamf Protect API Client password/secret (shown once when created)."
  type        = string
  sensitive   = true
}

# ── Jamf Platform (Blueprints) ───────────────────────────────
variable "jamfplatform_base_url" {
  description = "Jamf Platform API gateway for the tenant's region: https://us.apigw.jamf.com, https://eu.apigw.jamf.com, or https://apac.apigw.jamf.com."
  type        = string
  default     = "https://us.apigw.jamf.com"
}

variable "jamfplatform_client_id" {
  description = "Jamf Platform API client ID (created in Jamf Account, not Jamf Pro)."
  type        = string
  default     = ""
  sensitive   = true
}

variable "jamfplatform_client_secret" {
  description = "Jamf Platform API client secret (shown once when created)."
  type        = string
  default     = ""
  sensitive   = true
}

variable "jamfplatform_tenant_id" {
  description = "Jamf Platform tenant UUID for this client."
  type        = string
  default     = ""
}

variable "enable_software_update_blueprints" {
  description = "Create the two macOS software update Blueprints. Set false if the client has no Platform API access."
  type        = bool
  default     = true
}

variable "software_update_minor_days" {
  description = "Days after release to enforce minor macOS updates."
  type        = number
  default     = 14
}

variable "software_update_major_days" {
  description = "Days after release to enforce major macOS upgrades."
  type        = number
  default     = 30
}

variable "software_update_install_time" {
  description = "Local device time (HH:mm) when enforced updates install."
  type        = string
  default     = "23:45"
}

variable "software_update_device_group_name" {
  description = "Platform device group the blueprints target."
  type        = string
  default     = "All Managed Clients"
}

variable "enable_jamf_protect" {
  description = "Deploy the Jamf Protect baseline."
  type        = bool
  default     = true
}

variable "jamf_protect_mode" {
  description = "'Block and report' (production) or 'Report only' (monitor-first rollout)."
  type        = string
  default     = "Block and report"
}

variable "deploy_jamf_protect_profile" {
  description = "Deploy the Protect plan's config profile via Jamf Pro. OFF by default — deploy it from the Protect console instead (provider profile generation has issues without the Platform-level API)."
  type        = bool
  default     = false
}

variable "client_checkin_frequency" {
  description = "Minutes between Jamf client check-ins. MSP standard: 15. Allowed: 5, 15, 30, 60."
  type        = number
  default     = 15
}

# ── Security baseline & enrollment ───────────────────────────
variable "enable_security_baseline" {
  description = "FileVault + escrow, screen lock, firewall, stale-device group."
  type        = bool
  default     = true
}

variable "screen_lock_idle_minutes" {
  description = "Idle minutes before screen lock."
  type        = number
  default     = 15
}

variable "enable_passcode_blueprint" {
  description = "Passcode policy Blueprint (needs Platform API creds)."
  type        = bool
  default     = true
}

variable "passcode_min_length" {
  description = "Minimum password length."
  type        = number
  default     = 8
}

variable "enable_cis_benchmark" {
  description = "CIS Level 1 benchmark, all controls, MONITOR/report-only (never enforced)."
  type        = bool
  default     = true
}

variable "enable_prestage" {
  description = "Create the ADE/zero-touch PreStage (ABM link must exist first)."
  type        = bool
  default     = true
}

variable "ade_instance_id" {
  description = "ADE instance ID (usually '1')."
  type        = string
  default     = "1"
}

variable "msp_admin_username" {
  description = "Hidden MSP service admin created on EVERY Mac."
  type        = string
  default     = "msp_admin"
}

variable "msp_admin_password" {
  description = "Per-client password for the MSP service admin (required)."
  type        = string
  default     = ""
  sensitive   = true
}

variable "support_email" {
  description = "Support email shown during enrollment."
  type        = string
  default     = "helpdesk@example.com"
}

# ── EDR: Huntress or SentinelOne ─────────────────────────────
variable "edr_provider" {
  description = "'huntress', 'sentinelone', or 'none'."
  type        = string
}

variable "huntress_account_key" {
  description = "Huntress Account Key. Only needed when edr_provider = 'huntress'."
  type        = string
  default     = ""
  sensitive   = true
}

variable "huntress_organization_key" {
  description = "Huntress Organization Key for this client. Only needed when edr_provider = 'huntress'."
  type        = string
  default     = ""
}

variable "sentinelone_site_token" {
  description = "SentinelOne Site Token. Only needed when edr_provider = 'sentinelone'."
  type        = string
  default     = ""
  sensitive   = true
}

variable "sentinelone_package_path" {
  description = "Path to the local S1 installer pkg (e.g. ../../packages/Sentinel-Release_xxx.pkg). Uploaded to JCDS automatically. Required when edr_provider = 'sentinelone'."
  type        = string
  default     = ""
}

variable "huntress_package_path" {
  description = "Optional path to a local Huntress pkg (offline fallback upload only)."
  type        = string
  default     = ""
}

# ── Splashtop ────────────────────────────────────────────────
variable "enable_splashtop" {
  description = "Deploy Splashtop Streamer scaffolding."
  type        = bool
  default     = true
}

variable "splashtop_deploy_code" {
  description = "Splashtop deploy (stream) code for this client."
  type        = string
  default     = ""
  sensitive   = true
}

variable "splashtop_package_path" {
  description = "Path to the local Composer-built Splashtop deploy pkg (e.g. ../../packages/SplashtopStreamerDeploy.pkg). Uploaded to JCDS automatically. Required when enable_splashtop = true."
  type        = string
  default     = ""
}

# ── Self Service apps ────────────────────────────────────────
variable "common_apps_scope" {
  description = "'all' (default): common apps visible to everyone in Self Service, auto-patched where installed. 'installed_only': auto-patch existing installs only."
  type        = string
  default     = "all"
}

variable "is_1password_customer" {
  description = "true = push 1Password to all Macs and keep it updated."
  type        = bool
  default     = false
}

variable "app_suite" {
  description = "'auto' follows idp_provider (entra -> Microsoft 365 suite, google -> Google apps). Override: 'microsoft', 'google', 'none'."
  type        = string
  default     = "auto"
}

# ── Jamf Connect: Entra ID or Google Workspace ───────────────
variable "idp_provider" {
  description = "'entra', 'google', or 'none' (client does not receive Jamf Connect)."
  type        = string
}

variable "jamf_connect_oidc_client_id" {
  description = "OIDC client ID from the IdP app registration for Jamf Connect. Leave empty for 'none'."
  type        = string
  default     = ""
}

variable "jamf_connect_entra_tenant_id" {
  description = "Entra Directory (tenant) ID. Required for 'entra', leave empty for 'google'."
  type        = string
  default     = ""
}

variable "jamf_connect_redirect_uri" {
  description = "OIDC redirect URI registered on the IdP app."
  type        = string
  default     = "https://127.0.0.1/jamfconnect"
}

variable "jamf_connect_license_b64" {
  description = "Optional Jamf Connect license file, base64-encoded. Empty = skip license profile."
  type        = string
  default     = ""
  sensitive   = true
}

variable "jamf_connect_deny_local" {
  description = "Force all logins through the IdP (excluded accounts still allowed)."
  type        = bool
  default     = true
}

variable "jamf_connect_excluded_local_accounts" {
  description = "Extra local accounts excluded from DenyLocal (PreStage admin auto-included)."
  type        = list(string)
  default     = []
}

variable "jamf_connect_admin_group" {
  description = "IdP group granting local admin (empty = all users standard)."
  type        = string
  default     = ""
}

variable "jamf_connect_migrate" {
  description = "Takeover clients: link existing local accounts to IdP at first login."
  type        = bool
  default     = false
}

variable "jamf_connect_help_url" {
  description = "Help button URL at the login window."
  type        = string
  default     = "https://example.com"
}

variable "enable_platform_sso" {
  description = "Entra Platform SSO alongside Jamf Connect (Entra clients only; ignored otherwise)."
  type        = bool
  default     = true
}

variable "company_portal_package_path" {
  description = "Path to the local Company Portal pkg (e.g. ../../packages/CompanyPortal-Installer.pkg). Required when Platform SSO is on for an Entra client."
  type        = string
  default     = ""
}

variable "enable_jamf_connect_menubar" {
  description = "Deploy the menu bar profile too (validate the template first — see README)."
  type        = bool
  default     = false
}
